export const blue='#080DE0'
export const white='#FFFFFF'
export const black='#000000'
export const gray='#52577F'
export const lightGray='#E9ECEF'
export const lightLightGray='#F9FAFA'
export const lightBlueGray='#F2F2FE'
